from covid_csv_index_constants import LIST_TOTALCASES_INDEX, LIST_TOTALTESTS_INDEX, LIST_TOTALDEATHS_INDEX, LIST_NEWCASES_INDEX, LIST_NEWTESTS_INDEX

CSV_INDEX_DESCRIPTIONS = [
    f"Total cases - {LIST_TOTALCASES_INDEX}", 
    f"New cases - {LIST_NEWCASES_INDEX}",
    f"Total deaths - {LIST_TOTALDEATHS_INDEX}",
    f"Total tests - {LIST_TOTALTESTS_INDEX}",
    f"New tests - {LIST_NEWTESTS_INDEX}"]